server:
  port: 7071

spring:
  data:
    mongodb:
      host: localhost
      port: 27020
      username: java13user
      password: root
      database: userdb

jwt:
  secretKey: ${java13secretkey}
  audience: ${java13audience}
  issuer:   ${java13issuer}
